name="Edson"
caracter="a"
caracter_2='b'
caracter_3='''c'''
nombre_2='''Edson
Vargas'''

first_name="Edson"
last_name="Vargas"
print(name)
print(caracter)
print(caracter_2)
print(caracter_3)
print(nombre_2)
print(type(name))
print(type(caracter))
print(type(caracter_2))
print(type(caracter_3))
print(name[0])
print(name[1])
print(name[2])
print(first_name + " " + last_name)
print(len(name))
print(len(first_name))
print(len(last_name))
print(name.lower())
print(name.upper())
print(name.capitalize())
print(name.strip())